/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeritasVault } from "./VeritasVault";
export * as factories from "./factories";
export { VeritasVault__factory } from "./factories/VeritasVault__factory";
