/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VeritasVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "depositFunds"
      | "logEvidence"
      | "payoutClaim"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClaimPaid" | "EvidenceLogged" | "FundsDeposited"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "logEvidence",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "payoutClaim",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoutClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ClaimPaidEvent {
  export type InputTuple = [
    claimId: string,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    claimId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceLoggedEvent {
  export type InputTuple = [
    claimId: string,
    evidenceHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    evidenceHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    claimId: string;
    evidenceHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeritasVault extends BaseContract {
  connect(runner?: ContractRunner | null): VeritasVault;
  waitForDeployment(): Promise<this>;

  interface: VeritasVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  depositFunds: TypedContractMethod<[], [void], "payable">;

  logEvidence: TypedContractMethod<
    [claimId: string, evidenceHash: string],
    [void],
    "nonpayable"
  >;

  payoutClaim: TypedContractMethod<
    [recipient: AddressLike, claimId: string],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "logEvidence"
  ): TypedContractMethod<
    [claimId: string, evidenceHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payoutClaim"
  ): TypedContractMethod<
    [recipient: AddressLike, claimId: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ClaimPaid"
  ): TypedContractEvent<
    ClaimPaidEvent.InputTuple,
    ClaimPaidEvent.OutputTuple,
    ClaimPaidEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceLogged"
  ): TypedContractEvent<
    EvidenceLoggedEvent.InputTuple,
    EvidenceLoggedEvent.OutputTuple,
    EvidenceLoggedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;

  filters: {
    "ClaimPaid(string,address,uint256)": TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;
    ClaimPaid: TypedContractEvent<
      ClaimPaidEvent.InputTuple,
      ClaimPaidEvent.OutputTuple,
      ClaimPaidEvent.OutputObject
    >;

    "EvidenceLogged(string,string,uint256)": TypedContractEvent<
      EvidenceLoggedEvent.InputTuple,
      EvidenceLoggedEvent.OutputTuple,
      EvidenceLoggedEvent.OutputObject
    >;
    EvidenceLogged: TypedContractEvent<
      EvidenceLoggedEvent.InputTuple,
      EvidenceLoggedEvent.OutputTuple,
      EvidenceLoggedEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
  };
}
